### ISSUE TITLE
Update erases downloaded models

### ISSUE THREAD

**Issue by muchachagrande** [nextcloud/stt_whisper#12]
Hi, I've just updated to the last version and I realize that downloaded models were erased.
Is not a big problem as one can download them again but may be there is a way to make already downloaded models survive the updates.

**Comment by kyteinsky** [comment]
Hi @muchachagrande, I ran the model at v1.0.6, upgraded to v1.0.7 and ran again. It does not lose any downloaded models. v1.0.7 to master also does not show this, neither does the code have any such hints.  
If it occurs again, please consider opening a new issue.

**Comment by marcelklehr** [comment]
@kyteinsky How did you update? I believe this is an issue with all AI apps that I've created so far

**Comment by kyteinsky** [comment]
I was using a local git repo. I should probably try with an app store downloaded version.

**Comment by muchachagrande** [comment]
I use the app store, so may be the problem is only with it.
