### ISSUE TITLE
faster-whisper vs whisper.cpp?

### ISSUE THREAD

**Issue by Skollolol** [nextcloud/stt_whisper#16]
Hey,
first, let me thank you for your work, I'm very excited about this project.
Seeing how [stt_helper](https://github.com/nextcloud/stt_helper) is basically there, this small scale computer janitor, staring down a bunch of BA students looking to transcribe interviews for their qualitative research module, was wondering if [faster-whisper](https://github.com/guillaumekln/faster-whisper) could be an option to increase performance.

**Comment by marcelklehr** [comment]
This app is now deprecated in favor of https://github.com/nextcloud-releases/stt_whisper2 which uses faster whisper :tada:
