### ISSUE TITLE
'Make' test fails for stt-whisper as home/user

### ISSUE THREAD

**Issue by cgiakmoz** [nextcloud/stt_whisper#19]
My aim is to install the stt_whisper on my nextcloud (Version 27.1.1) on my Debian 11 Server ,as a non-root user.

When I go to the bash shell on the server, and attempt 'make test', the process for installing stt__whisper v1.0.6 keeps failing.

I commence by installing the stt-whisper app within NextCloud WebAdmin. This properly sets the correct user "www-data" and other permissions. 

Then - in the bash shell on the server - I attempt 'make test' the process for installing stt__whisper v1.0.6. But it fails with errors. (see paste1.txt below)

My plan was to copy the completed make install or substitute the nextcloud/apps/stt_whisper folder from my /home/user folder and manually chown to www-data to fix the user & permissions.

See the excerpt/attachment stdout pasted below
 
SUMMARY of steps to cause error:
- I proceed to do a 'MAKE' for stt_whisper in my /home/user directory as follows. 

$>  cd ~/
$>  mkdir gits
$>  git clone https://github.com/nextcloud/stt_whisper.git
$>  cd stt_whisper
$> sudo apt install phpunit       ## This is necessary since neither PHPUNIT exists in /bin/phpunit ... NOR does the phpunit.xml file exist in the stt_whisper app. 
$>  make clean
$>  make test

Unfortunately. The process fails as follows:
[paste1.txt](https://github.com/nextcloud/stt_whisper/files/12726607/paste1.txt)

And here is the output when I try an actual   "make" (not 'make test' command)
[paste.txt](https://github.com/nextcloud/stt_whisper/files/12726686/paste.txt)

NOTE:  I have a "PerfectServer" Rig (based on HowToForge https://www.howtoforge.com/how-to-install-nextcloud-with-ispconfig/) and installed on a Proxmox hypervisor

**Comment by kyteinsky** [comment]
Hello,
If you just want to install the app, just install it from the "Apps" page inside Nextcloud's web UI. Then you'd need to download a model file using the command line:
```sh
occ stt_whisper:download-models [model-name]
```
`mode-name` can be small, medium or large.

The other steps mentioned are to manually install the app and are not required if you just want to use it.  
`make test` was carried over from other projects and is supposed to test the php app from a development perspective. We don't have tests yet so it was redundant and has been removed.

Hope that helps.

**Comment by marcelklehr** [comment]
This app is now deprecated in favor of https://github.com/nextcloud-releases/stt_whisper2 which is documented at https://docs.nextcloud.com/server/latest/admin_manual/ai/index.html
