### ISSUE TITLE
How to "make" the app for my server's processor architecture

### ISSUE THREAD

**Issue by funky123** [nextcloud/stt_whisper#20]
i am running nc in a lxc env and i may need to compile whisper myself. according to the doc i may need to "make" it myself.
but there may be an other issue using whisper at lxc?

![image](https://github.com/nextcloud/stt_whisper/assets/12056510/43a17ff3-0b68-46bd-a12b-f9533d9e503c)

**Comment by marcelklehr** [comment]
There shouldn't be any issues due to LXC, just make sure your LXC container follows the requirements in the README.

**Comment by funky123** [comment]
since LXC dont Supports AVX there is no chance of running Whipser. just in case some other ppl are searching for a solution.
