### ISSUE TITLE
Feat: Email Notification Event on Transcription Completion

### ISSUE THREAD

**Issue by farhills** [nextcloud/stt_whisper#36]
Request:  in my workflow, Whisper is transcribing dictations which ultimately become word document reports.  It would be great to have an email notification which includes the full transcription in the email body.  Currently I grab the text through the web browser notifications which is a bit unreliable and easy to misplace if multiple are triggered at the same time.

The transcriptions are triggered through talk, so if this is more appropriately posted there, let me know and I'll close this issue.

Thanks for considering!

![image](https://github.com/nextcloud/stt_whisper/assets/83388006/9c90d36e-525a-42f6-af40-86691847d719)

**Comment by marcelklehr** [comment]
Yeah, please submit this with the talk repo.
