### ISSUE TITLE
Sometimes it fails with the following message: "Failed to schedule transcription"

### ISSUE THREAD

**Issue by nc-fkl** [nextcloud/stt_whisper#37]
Hi,

when using stt_whisper, it often fails with "Failed to schedule transcription."

![err](https://github.com/nextcloud/stt_whisper/assets/149385388/f79498e7-2666-483f-849d-d07df935c7d5)

Same happens when using a localy stored audio file like "test_audio.mp3"

I then tried to use it via the text application and it worked there. I switched back to "talk" to use text to speech there again via "/" and selecting text to speech and then it was working there also.

After logging out and logging in again, it failed again with the screenshot from above with "live recording", then i used a locally stored audio file and that worked. I then switched back to "live recording" speech to text and then it worked there also.

So its currently unpredictable whenever it works or not, also the error message that "Javascript isnt enabled" is misleading. For me it looks like the frontend doesnt pass the file correctly to the backend somehow, but just sometimes not always.

The corresponding part of the nextcloud.log shows the following, so it seems that it passes a folder instead of the selected file (but the file is selected in the frontend):

`{
  "reqId": "hIorm60M3sUhZXn8DZ78",
  "level": 3,
  "time": "2024-04-04T07:49:49+00:00",
  "remoteAddr": "2a02:810d:b5bf:e1d8:1f2d:965a:eb01:946b",
  "user": "admin",
  "app": "index",
  "method": "POST",
  "url": "/apps/stt_helper/transcribeFile",
  "message": "OC\\SpeechToText\\SpeechToTextManager::scheduleFileTranscription(): Argument #1 ($file) must be of type OCP\\Files\\File, OC\\Files\\Node\\Folder given, called in /opt/nextcloud/28.0.0/apps/stt_helper/lib/Service/SttService.php on line 108 in file '/opt/nextcloud/28.0.0/lib/private/SpeechToText/SpeechToTextManager.php' line 95",
  "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0",
  "version": "28.0.3.2",
  "exception": {
    "Exception": "Exception",
    "Message": "OC\\SpeechToText\\SpeechToTextManager::scheduleFileTranscription(): Argument #1 ($file) must be of type OCP\\Files\\File, OC\\Files\\Node\\Folder given, called in /opt/nextcloud/28.0.0/apps/stt_helper/lib/Service/SttService.php on line 108 in file '/opt/nextcloud/28.0.0/lib/private/SpeechToText/SpeechToTextManager.php' line 95",
    "Code": 0,
    "Trace": [
      {
        "file": "/opt/nextcloud/28.0.0/lib/private/AppFramework/App.php",
        "line": 184,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          [
            "OCA\\Stt\\Controller\\SttController"
          ],
          "transcribeFile"
        ]
      },
      {
        "file": "/opt/nextcloud/28.0.0/lib/private/Route/Router.php",
        "line": 315,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Stt\\Controller\\SttController",
          "transcribeFile",
          [
            "OC\\AppFramework\\DependencyInjection\\DIContainer"
          ],
          [
            "stt_helper.stt.transcribeFile"
          ]
        ]
      },
      {
        "file": "/opt/nextcloud/28.0.0/lib/base.php",
        "line": 1069,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/apps/stt_helper/transcribeFile"
        ]
      },
      {
        "file": "/opt/nextcloud/28.0.0/index.php",
        "line": 39,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/opt/nextcloud/28.0.0/lib/private/AppFramework/Http/Dispatcher.php",
    "Line": 169,
    "Previous": {
      "Exception": "TypeError",
      "Message": "OC\\SpeechToText\\SpeechToTextManager::scheduleFileTranscription(): Argument #1 ($file) must be of type OCP\\Files\\File, OC\\Files\\Node\\Folder given, called in /opt/nextcloud/28.0.0/apps/stt_helper/lib/Service/SttService.php on line 108",
      "Code": 0,
      "Trace": [
        {
          "file": "/opt/nextcloud/28.0.0/apps/stt_helper/lib/Service/SttService.php",
          "line": 108,
          "function": "scheduleFileTranscription",
          "class": "OC\\SpeechToText\\SpeechToTextManager",
          "type": "->",
          "args": [
            [
              "OC\\Files\\Node\\Folder"
            ],
            "admin",
            "stt_helper"
          ]
        },
        {
          "file": "/opt/nextcloud/28.0.0/apps/stt_helper/lib/Controller/SttController.php",
          "line": 199,
          "function": "transcribeFile",
          "class": "OCA\\Stt\\Service\\SttService",
          "type": "->",
          "args": [
            "/",
            "admin"
          ]
        },
        {
          "file": "/opt/nextcloud/28.0.0/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 230,
          "function": "transcribeFile",
          "class": "OCA\\Stt\\Controller\\SttController",
          "type": "->",
          "args": [
            "/"
          ]
        },
        {
          "file": "/opt/nextcloud/28.0.0/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 137,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            [
              "OCA\\Stt\\Controller\\SttController"
            ],
            "transcribeFile"
          ]
        },
        {
          "file": "/opt/nextcloud/28.0.0/lib/private/AppFramework/App.php",
          "line": 184,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            [
              "OCA\\Stt\\Controller\\SttController"
            ],
            "transcribeFile"
          ]
        },
        {
          "file": "/opt/nextcloud/28.0.0/lib/private/Route/Router.php",
          "line": 315,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::",
          "args": [
            "OCA\\Stt\\Controller\\SttController",
            "transcribeFile",
            [
              "OC\\AppFramework\\DependencyInjection\\DIContainer"
            ],
            [
              "stt_helper.stt.transcribeFile"
            ]
          ]
        },
        {
          "file": "/opt/nextcloud/28.0.0/lib/base.php",
          "line": 1069,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->",
          "args": [
            "/apps/stt_helper/transcribeFile"
          ]
        },
        {
          "file": "/opt/nextcloud/28.0.0/index.php",
          "line": 39,
          "function": "handleRequest",
          "class": "OC",
          "type": "::",
          "args": []
        }
      ],
      "File": "/opt/nextcloud/28.0.0/lib/private/SpeechToText/SpeechToTextManager.php",
      "Line": 95
    },
    "message": "OC\\SpeechToText\\SpeechToTextManager::scheduleFileTranscription(): Argument #1 ($file) must be of type OCP\\Files\\File, OC\\Files\\Node\\Folder given, called in /opt/nextcloud/28.0.0/apps/stt_helper/lib/Service/SttService.php on line 108 in file '/opt/nextcloud/28.0.0/lib/private/SpeechToText/SpeechToTextManager.php' line 95",
    "exception": {},
    "CustomMessage": "OC\\SpeechToText\\SpeechToTextManager::scheduleFileTranscription(): Argument #1 ($file) must be of type OCP\\Files\\File, OC\\Files\\Node\\Folder given, called in /opt/nextcloud/28.0.0/apps/stt_helper/lib/Service/SttService.php on line 108 in file '/opt/nextcloud/28.0.0/lib/private/SpeechToText/SpeechToTextManager.php' line 95"
  }
}
`

Also its possible to just select a folder and press "Choose" which would produce the same issue as mentioned above:

https://github.com/nextcloud/stt_whisper/assets/149385388/520181ba-ceab-40d6-9656-6b2a98e0d5d0

It would be more user friendly if its not possible to click the "Choose" Button (Greyed out) or if its possible to click it, then it should make a popup notification that a not supported file/folder is was selected and it cant be execute with that source.

**Comment by marcelklehr** [comment]
(stt_helper is deprecated)

**Comment by marcelklehr** [comment]
This app is now deprecated in favor of https://github.com/nextcloud-releases/stt_whisper2 which is documented at https://docs.nextcloud.com/server/latest/admin_manual/ai/index.html
