### ISSUE TITLE
When installed from the appstore the binaries are not executable

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/stt_whisper#5]
Needed to execute this:
```
chmod u+x /var/www/nextcloud/apps/stt_whisper/node_modules/ffmpeg-static/ffmpeg
chmod u+x /var/www/nextcloud/apps/stt_whisper/bin/main
chmod u+x /var/www/nextcloud/apps/stt_whisper/bin/main-musl
```

But would be better if they are in the tar with u+x applied

**Comment by nickvergessen** [comment]
You might be right:
https://github.com/nextcloud/talk_matterbridge/blob/master/lib/Migration/RegisterBinary.php#L76-L78

**Comment by selimb86** [comment]
I was using AIO and had to create a link from custom_apps to apps fodler
