### ISSUE TITLE
Smart picker integration

### ISSUE THREAD

**Issue by nathanhaines** [nextcloud/stt_whisper#8]
I upgraded my Nextcloud server to 27.0.0 following the launch event, and downloaded and enabled stt_whisper and installed the large and medium models.  Then I went into settings and everything looked good.

However, I cannot seem to find a way to trigger a dictation event.  Not in Text, Mail, or Nextcloud Office.

OpenAI integration surfaces Whisper as an option (but of course it fails afterward with no API key).

Is there documentation on how to enable local Whisper AI translation on an existing server?

**Comment by selimb86** [comment]
Same here with the Large model

**Comment by marcelklehr** [comment]
Hey there :wave: 

This app only implements a SpeechToText *API* provider. It doesn't implement a frontend, ie. no smart picker. The SpeechToText API is currently only used by the Talk app to transcribe meeting recordings. We are currently still debating how best to provide a generic speech-to-text smart picker. Perhaps we will create a new app that offers speech-to-text smart picker and NC flow integrations. This would then work with all Speech-to-Text providers.

cc @julien-nc

**Comment by selimb86** [comment]
@marcelklehr Thanks for the clarification. I thought it was providing the same smart picker that was presented during Hub 5 yesterday.

**Comment by Skollolol** [comment]
Aw, too bad.
Consider this a request for that separate app, then ;)

**Comment by julien-nc** [comment]
Hey there, the [stt_helper](https://github.com/nextcloud/stt_helper) app is about to be published. It contains a smart picker provider that uses the STT providers. If you're comfortable with building it from sources, you can already try it.
